#ifndef DLMS_ERROR_CODE_H
#define DLMS_ERROR_CODE_H

typedef enum
{
    DLMS_ERROR_TYPE_EXCEPTION_RESPONSE = 0x80000000,
    DLMS_ERROR_TYPE_CONFIRMED_SERVICE_ERROR = 0x40000000,
    DLMS_ERROR_TYPE_COMMUNICATION_ERROR = 0x20000000
} DLMS_ERROR_TYPE;

typedef enum
{
    DLMS_EXCEPTION_SERVICE_ERROR_INVOCATION_COUNTER_ERROR = 6
} DLMS_EXCEPTION_SERVICE_ERROR;

typedef enum
{
    DLMS_ERROR_CODE_UNACCEPTABLE_FRAME = -3,
    DLMS_ERROR_CODE_REJECTED = -2,
    DLMS_ERROR_CODE_FALSE = -1,
    DLMS_ERROR_CODE_OK = 0,
    DLMS_ERROR_CODE_READ_WRITE_DENIED = 3,
    DLMS_ERROR_CODE_INCONSISTENT_CLASS_OR_OBJECT = 9,
    DLMS_ERROR_CODE_UNMATCH_TYPE = 12,
    DLMS_ERROR_CODE_DATA_BLOCK_NUMBER_INVALID = 19,
    DLMS_ERROR_CODE_UNKNOWN,
    DLMS_ERROR_CODE_RECEIVE_FAILED,
    DLMS_ERROR_CODE_NOT_IMPLEMENTED,
    DLMS_ERROR_CODE_INVALID_COMMAND,
    DLMS_ERROR_CODE_INVALID_PARAMETER,
    DLMS_ERROR_CODE_OUTOFMEMORY,
    DLMS_ERROR_CODE_INVALID_CLIENT_ADDRESS,
    DLMS_ERROR_CODE_INVALID_SERVER_ADDRESS,
    DLMS_ERROR_CODE_INVALID_VERSION_NUMBER,
    DLMS_ERROR_CODE_WRONG_CRC,
    DLMS_ERROR_CODE_INVALID_TAG,
    DLMS_ERROR_CODE_REJECTED_PERMAMENT,
    DLMS_ERROR_CODE_REJECTED_TRANSIENT,
    DLMS_ERROR_CODE_NO_REASON_GIVEN,
    DLMS_ERROR_CODE_APPLICATION_CONTEXT_NAME_NOT_SUPPORTED,
    DLMS_ERROR_CODE_AUTHENTICATION_FAILURE,
    DLMS_ERROR_CODE_INVALID_INVOKE_ID,
    DLMS_ERROR_CODE_INVALID_DECIPHERING_ERROR,
} DLMS_ERROR_CODE;

#endif